### ISSUE TITLE
Fix Artifactory-maven-plugin config

### ISSUE THREAD

**Issue by vatbub** [vatbub/defaultRepo#8]
The artifactory maven recoreder fails every deploy build with the following exception:

```
[ERROR] org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 

java.lang.RuntimeException: Error occurred while publishing artifact to Artifactory: /home/travis/build/vatbub/safeAPIKeyStore/pom.xml.

 Skipping deployment of remaining artifacts (if any) and build info.

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:274)

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:108)

	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:139)

	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)

	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)

	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)

	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)

	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)

	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)

	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)

	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Caused by: java.io.IOException: Failed to deploy file: HTTP response code: 409. HTTP response message: Conflict

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.throwHttpIOException(ArtifactoryBuildInfoClient.java:644)

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:519)

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:294)

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:272)

	... 19 more

[ERROR] Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: Error occurred while publishing artifact to Artifactory: /home/travis/build/vatbub/safeAPIKeyStore/pom.xml.

[ERROR]  Skipping deployment of remaining artifacts (if any) and build info. Failed to deploy file: HTTP response code: 409. HTTP response message: Conflict

[ERROR] -> [Help 1]

org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 

	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)

	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)

	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)

	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)

	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Caused by: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 

	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:150)

	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)

	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)

	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)

	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)

	... 11 more

Caused by: java.lang.RuntimeException: Error occurred while publishing artifact to Artifactory: /home/travis/build/vatbub/safeAPIKeyStore/pom.xml.

 Skipping deployment of remaining artifacts (if any) and build info.

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:274)

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:108)

	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:139)

	... 17 more

Caused by: java.io.IOException: Failed to deploy file: HTTP response code: 409. HTTP response message: Conflict

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.throwHttpIOException(ArtifactoryBuildInfoClient.java:644)

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:519)

	at org.jfrog.build.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:294)

	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:272)

	... 19 more
```

**Comment by vatbub** [comment]
Not fixed

**Comment by vatbub** [comment]
It now seems to not upload the pom at all

**Comment by vatbub** [comment]
Issue still occurrs
